CREATE TABLE PERMISSIONS (
    ROLE VARCHAR(255) PRIMARY KEY,
    CAN_ADD_PRODUCT_IN_CART BOOLEAN NOT NULL,
    CAN_DELETE_PRODUCT_FROM_CART BOOLEAN NOT NULL,
    CAN_SEE_CART BOOLEAN NOT NULL,
    CAN_ORDER BOOLEAN NOT NULL,
    CAN_ADD_NEW_PRODUCT BOOLEAN NOT NULL,
    CAN_EDIT_PRODUCT BOOLEAN NOT NULL,
    CAN_DELETE_PRODUCT BOOLEAN NOT NULL,
    CAN_EDIT_CATEGORIES BOOLEAN NOT NULL,
    CAN_SEE_PRODUCER BOOLEAN NOT NULL,
    CAN_ADD_NEW_PRODUCER BOOLEAN NOT NULL
);