INSERT INTO PERMISSIONS VALUES('Администратор', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);
INSERT INTO PERMISSIONS VALUES('Авторизованный пользователь', TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE);
INSERT INTO PERMISSIONS VALUES('Работник магазина', FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE);
